# Generated by Django 5.2.8 on 2026-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduateattribute',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='graduateattribute',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='graduateattribute',
            name='program',
        ),
    ]
